# Generated by Django 4.2 on 2023-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('未経験', '未経験'), ('経験者', '経験者')], default='未経験', max_length=10),
        ),
    ]
